version: '3.10'
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    command: gunicorn djangoreactproject.wsgi --bind 0.0.0.0:8000

    expose:
      - 8000
    env_file:
      - ./backend/.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  static_volume: