version: '3.10'
services:
  django:
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    build:
      context: ./backend
    volumes:
      - static_volume:/home/app/web/django_static
    command: gunicorn djangoreactproject.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env_db

  nginx:
    restart: unless-stopped
    build:
      context: ./frontend
    volumes:
      - static_volume:/home/app/web/django_static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
