version: '3.10'
services:
  django:
    restart: unless-stopped
    build:
      context: ./backend
    volumes:
      - static_volume:/home/app/web/django_static

    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env_db

  nginx:
    restart: unless-stopped
    build:
      context: ./frontend
    volumes:
      - static_volume:/app/django_static
    ports:
      - 8080:8080
    depends_on:
      - django
volumes:
  postgres_data:
  static_volume:
