version: '3.10'
services:
  django:
#    restart: unless-stopped
    environment:
      - ENV_FILENAME=.env.prod
    build:
      context: .
    volumes:
      - static_volume:/home/app/web/django_static
#    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#    entrypoint: gunicorn djangoreactproject.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    entrypoint: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - db-net
  nginx:
    restart: unless-stopped
    build:
      context: ./frontend
    volumes:
      - static_volume:/home/app/web/django_static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
    networks:
      - db-net

volumes:
  static_volume: {}

networks:
  db-net:
    driver: bridge