version: '3.8'
services:
  django:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/home/backend/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - backend/.env.dev

#    volumes:
#          django:
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env_db

volumes:
  postgres_data: