version: '3.10'
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev