# Generated by Django 4.0 on 2022-01-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synergy_users', '0004_alter_synergyuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synergyuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', related_query_name='users', to='synergy_users.synergygroup'),
        ),
    ]
